version: '3.8'

services:
  backend:
    container_name: development
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3001:3001'
    depends_on:
      - postgres
    env_file:
      - .env.development

  postgres:
    image: postgres:alpine3.19
    container_name: database-development
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres_dev:/var/lib/postgresql/data

volumes:
  postgres_dev:
    name: ikdb-development
